name: Build and release Systemd sysext images
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    container:  mediadepot/flatcar-developer:${{ matrix.flatcarversion }}
    strategy:
      max-parallel: 6
      matrix:
        flatcarversion: ["3510.2.6"]
    permissions:
      # allow the action to create a release
      contents: write
    steps:
      # checkout the sources
      - uses: actions/checkout@v3
      # build the images and generate a manifest
      - name: build
        run: |
          set -euo pipefail

          images=(
              "zfs-2.1.11-${{ matrix.flatcarversion }}"
          )

          for image in ${images[@]}; do
              IFS="-" read -ra parts <<< "$image"
              component="${parts[0]}"
              version="${parts[1]}"

              if [ "${#parts[@]}" -eq 3 ]; then
                 flatcarversion="${parts[2]}"
              else
                 flatcarversion=""
              fi
 
              if [ -n "$flatcarversion" ]; then
                 "./create_${component}_sysext.sh" "${version}" "${component}" "${flatcarversion}"
              else
                 "./create_${component}_sysext.sh" "${version}" "${component}"
              fi
              mv "${component}.raw" "${image}.raw"
          done

          sha256sum *.raw > SHA256SUMS
      # create a Github release with the generated artifacts
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            SHA256SUMS
            *.raw
